---
title: "Text Mining"
author: "Atta Boateng"
date: "03-31-2024"
output: 
  html_document:
    figure_caption: yes

---

```{r echo=TRUE, results='asis'}
library(tidytext)

get_sentiments("afinn")

```

```{r echo=TRUE, results='asis'}
library(tidytext)

get_sentiments("bing")

```

```{r echo=TRUE, results='asis'}
library(tidytext)

get_sentiments("nrc")

```


```{r echo=TRUE, results='asis'}
library(janeaustenr)
library(dplyr)
library(stringr)

tidy_books <- austen_books() %>%
  group_by(book) %>%
  mutate(
    linenumber = row_number(),
    chapter = cumsum(str_detect(text, 
                                regex("^chapter [\\divxlc]", 
                                      ignore_case = TRUE)))) %>%
  ungroup() %>%
  unnest_tokens(word, text)


tidy_books
#austen_books()

```

```{r echo=TRUE, results='asis'}
nrc_joy <- get_sentiments("nrc") %>% 
  filter(sentiment == "joy")

tidy_books %>%
  filter(book == "Emma") %>%
  inner_join(nrc_joy) %>%
  count(word, sort = TRUE)

```


```{r echo=TRUE, results='asis'}
library(tidyr)

a <- get_sentiments("bing")
a

jane_austen_sentiment <- tidy_books %>%
  inner_join(get_sentiments("bing")) %>%
  count(book, index = linenumber %/% 80, sentiment) %>%
  pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) %>% 
  mutate(sentiment = positive - negative)

```




Getting the corpus and using the afinn sentiment

```{r echo=TRUE, results='asis'}
library(tidytext)
library(textdata)
library(gutenbergr)

#get_sentiments("nrc")

gutenberg_works(author =="Twain, Mark") %>% filter(gutenberg_id == "7100")

book <- gutenberg_download(7100)$text
book <- as.data.frame(book)

book <- book %>% mutate(rownumber = row_number()) %>% ungroup() %>% unnest_tokens(word,book)

```

Doing the sentiment analysis. The following are words that associated with fear.

```{r echo=TRUE, results='asis'}
library(tidytext)
library(textdata)
library(gutenbergr)

nrc_tired <- get_sentiments("nrc") %>% filter(sentiment == "fear")

twain_tidy <- book %>% inner_join(nrc_tired) 
twain_tidy


twain_tidy %>%count(word)
```


```{r echo=TRUE, results='asis'}
library(ggplot2)

a <- twain_tidy %>%count(word)

a %>% filter(n == max(a$n))
```

I was having issue plot the plot so for the analysis, I would trying to look at the most use word in the story which to attributed the author's favorite word while writing the story
