---
title: "R and SQL"
author: "Atta Boateng"
date: "02-07-2024"
output: 
  html_document:
    figure_caption: yes

---

```{r echo=FALSE, results='asis'}
library("RMySQL")
library(DBI)
library(dbplyr)
library(tidyverse)

conn <- dbConnect(MySQL(), user = 'atta.boatengsr67', password = 'atta.boatengsr67', dbname='atta.boatengsr67', host = 'cunydata607sql.mysql.database.azure.com');
```

```{r echo=TRUE, results='asis'}
library("RMySQL")
library(DBI)
library(dbplyr)
library(tidyverse)
library(knitr)


# #sql <- "CREATE TABLE MovieReview (
#       movieID int AUTO_INCREMENT PRIMARY KEY,
#       movieName varchar(255),
#       reviewName varchar(255),
#       movieRating int)"

sql <- "TRUNCATE TABLE MovieReview;";
dbGetQuery(conn, sql);

sql <- "SELECT * 
        FROM MovieReview";
#View(dbGetQuery(conn, sql))
kable(dbGetQuery(conn, sql))

sql <- "INSERT INTO MovieReview (movieName, reviewName, movieRating)
VALUES ('Avengers: Age of Ultron', 'Alex', 4);";

dbGetQuery(conn, sql);

sql <- "INSERT INTO MovieReview (movieName, reviewName, movieRating)
VALUES ('MacBeth', 'Tiana', 4);";

dbGetQuery(conn, sql);

sql <- "INSERT INTO MovieReview (movieName, reviewName, movieRating)
VALUES ('Wall-E', 'Atta', 5);";

dbGetQuery(conn, sql);

sql <- "INSERT INTO MovieReview (movieName, reviewName, movieRating)
VALUES ('Color Purple', 'Ophelia', 4);";

dbGetQuery(conn, sql);

sql <- "INSERT INTO MovieReview (movieName, reviewName, movieRating)
VALUES ('Terminator', 'Ebenezer', 3);";

dbGetQuery(conn, sql);

sql <- "INSERT INTO MovieReview (movieName, reviewName, movieRating)
VALUES ('Friday', 'Kobe', 4);";

dbGetQuery(conn, sql);

sql <- "SELECT * 
        FROM MovieReview";

data <- data.frame(dbGetQuery(conn, sql));

kable(data)


```

I would remove rows with missing data because I would not want to obscure the data set.
For example, if I wanted to find the average ratings of movies of the same title, row in which
the data is missing might give an inaccurate depiction of the ratings.
